---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r startup}
suppressPackageStartupMessages(library(tidyverse))
library(brms)
dat <- read_csv("data/virus_in_silenced.csv")
```

## CuP14 knockdown

### VDV2
```{r CuP14_VDV2}
CuP14_VDV2 <- filter(dat, Experiment == "CuP14_exp" & Gene == "VDV2")
ggplot(CuP14_VDV2, aes(Treatment, RQ)) + geom_point()
CuP14_VDV2_brms <-brm(bf(RQ ~ Treatment, sigma ~ Treatment), family=student, data = CuP14_VDV2)
plot(CuP14_VDV2_brms)
summary(CuP14_VDV2_brms)
hypothesis(CuP14_VDV2_brms, "TreatmentSilenced < 0") # directional hypothesis test that silenced is lower
```

### ARV2
```{r CuP14_ARV2}
CuP14_ARV2 <- filter(dat, Experiment == "CuP14_exp" & Gene == "ARV2")
ggplot(CuP14_ARV2, aes(Treatment, RQ)) + geom_point()
CuP14_ARV2_brms <-brm(bf(RQ ~ Treatment, sigma ~ Treatment), family=student, data = CuP14_ARV2)
plot(CuP14_ARV2_brms)
summary(CuP14_ARV2_brms)
hypothesis(CuP14_ARV2_brms, "TreatmentSilenced < 0")
```

### DWVa
```{r CuP14_DWVa}
CuP14_DWVa <- filter(dat, Experiment == "CuP14_exp" & Gene == "DWVa")
ggplot(CuP14_DWVa, aes(Treatment, RQ)) + geom_point()
CuP14_DWVa_brms <-brm(bf(RQ ~ Treatment, sigma ~ Treatment), family=student, data = CuP14_DWVa)
plot(CuP14_DWVa_brms)
summary(CuP14_DWVa_brms)
hypothesis(CuP14_DWVa_brms, "TreatmentSilenced < 0")
```